CREATE TABLE IF NOT EXISTS member (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NULL,
    location VARCHAR(50) NULL,
    role VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS lesson (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    method VARCHAR(50) NOT NULL,
    subject VARCHAR(100) NOT NULL,
    price VARCHAR(50) NOT NULL,
    rating VARCHAR(50) NULL,
    member BIGINT NOT NULL 
        CONSTRAINT lesson_member_fkey REFERENCES member
);

CREATE TABLE IF NOT EXISTS request_card (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    sender VARCHAR(50) NOT NULL,
    receiver VARCHAR(100) NOT NULL,
    message VARCHAR(50) NULL,
    PRIMARY KEY (id),
    lesson BIGINT NOT NULL
        CONSTRAINT request_card_lesson_fkey REFERENCES lesson
);